FROM rust:1.72.0-bullseye
SHELL ["/bin/bash", "-c"]

ENV RESULTS_DIR=/home/results

RUN apt update && apt install -y make clang-13 libdbus-glib-1-dev
RUN alias clang=clang-13; alias clang++=clang++-13

COPY src/ /home/src/
COPY Cargo.lock Cargo.toml /home/
WORKDIR /home/
RUN cargo build --release

COPY benchmarks/CBMC_utils/ /home/benchmarks/CBMC_utils/
COPY benchmarks/SIFF/ /home/benchmarks/SIFF/ 
COPY benchmarks/heusser_malacaria/ /home/benchmarks/heusser_malacaria/
COPY benchmarks/phan_malacaria/ /home/benchmarks/phan_malacaria/
COPY benchmarks/*.c benchmarks/*.h benchmarks/build_all.sh /home/benchmarks/
WORKDIR /home/benchmarks
RUN ./build_all.sh fuzz

RUN mkdir -p /home/results
COPY benchmarks/fuzz_all.sh /home/benchmarks/

ENV RUNTIME=43200
# ENV RUNTIME=3600

CMD /home/benchmarks/fuzz_all.sh
